### ISSUE TITLE
Provide the possibility to start the SDK without service

### ISSUE THREAD

**Issue by grizli245** [IPRoyal/android-pawns-sdk-demo#1]
It was already a great improvement to launch the SDK in a background service instead of being forced to use foreground service.
In my particular case, however, I already have a foreground service and would like to launch the SDK in that context. 
For this we would only need a very simple low-level start(), stop() and init(token) functionality.

**Comment by LaurynasM-iproyal** [comment]
Hello. Thanks for bringing this to our attention, but currently we are focused on providing our library as a separate service. Although we might consider adding this to our roadmap later in the future, especially if this feature request will receive more attention.
