### ISSUE TITLE
App detected containing virus due to Pawns sdk.

### ISSUE THREAD

**Issue by Ayman-apps** [IPRoyal/android-pawns-sdk-demo#4]
HI,
The app got rejected by Huawei Appstore as it contains virus.
Please find the below information:
App review results：
Your App is detected to carry virus: "ELF:Pawns-C [Tool]||mult". Please refer to the rule 2.1 of "AppGallery Review Guidelines": https://developer.huawei.com/consumer/en/doc/app/50104-02
[Suggestion]: Please check the apk file, code, third-party SDK or others to delete the virus-relevant contents.
[Test Environment]: Wi-Fi connection,Mate 30 Pro with EMUI 10.0，P20 with EMUI 9.0 ，Multilingual environment.

**Comment by Ayman-apps** [comment]
![Screenshot 2024-02-27 110853](https://github.com/IPRoyal/android-pawns-sdk-demo/assets/161304567/c333d890-3b11-472b-b76f-e3d565500f0b)

**Comment by LaurynasM-iproyal** [comment]
Unfortunately, we do not really support Huawei devices specifically, so we cannot provide a lot of help how to deal with Huawei AppGallery. We would suggest trying to submit a false positive report for SDK, if that is possible. If that does not seem to exist, then we suggest adding a disclaimer dialog in your application that uses this text:

**_"By using this app, you are agreeing to share your internet traffic, and, therefore, might incur various outcomes with it. The company shares your internet traffic with third-party IPRoyal Services FZE LLC operating Pawns.app. Thus, the usage of your internet sharing is governed by rules set by the following documents: [Link to Terms of Service] and [Link to Privacy Policy]. These documents outline the rules and regulations governing the use of Pawns.app and its functionalities “_**

By doing so, it will show publishers that you are informing user about your intents and gives you extra transparency. Also, we would suggest writing an explanation what our SDK does and that it is not a virus and added to your project on purpose. To explain the usage of service you can use text from our manifest file.

**_Allows to share internet traffic by modifying device's network settings to be used as a gateway for internet traffic. Device becomes a gateway which allows to send and receive internet traffic._**

**Comment by Ayman-apps** [comment]
Nothing related to Huawei AppGallery. It is detected as a virus on virustotal.com. Check the screenshot attached before identifying ELF trojan.
Also, I need these documents that you mentioned:
 [Link to Terms of Service] and [Link to Privacy Policy].

**Comment by LaurynasM-iproyal** [comment]
The reason why some anti virus softwares detect our SDK as a virus is because we are using device's internet connection and we are intercepting it. This sort of behavior or similar might be marked as suspicious. We are continuously contacting different anti virus companies and submitting false positive reports, but not all of them are responding. Currently there is nothing we can help you out with regarding these reports.
