### ISSUE TITLE
Using permission FOREGROUND_SERVICED_SPECIAL_USE in 1.1.1

### ISSUE THREAD

**Issue by Ayman-apps** [IPRoyal/android-pawns-sdk-demo#5]
Issue found in 1.1.1 that you are adding a permission FOREGROUND_SERVICED_SPECIAL_USE. This is very difficult to be approved by google play store. So can you just rely on "android.permission.FOREGROUND_SERVICE"  which doesnot need approval or even on "android.permission.FOREGROUND_SERVICE_DATA_SYNC" which we already got approval on it before?

If it is must, then we need a justification to be sent to Google play.

**Comment by Ayman-apps** [comment]
Hello,
Yes, we are having problems to submit app with this.
First of all, what justification and what to say in video declaration to google play store to accept this. We already got a massive efforts to approve the datasync.
As a temp solution/workaround, currently we deployed with version1.1.0 since we are not using Pawns in Foreground due to other issue already reported (showing the notification). So once we are able to use the it with Foreground , we will need to fix the permission as well.
Also, please have a look about the very important issue -virus issue-(already reported) as our app was just removed from Huawei app gallery and we had to submit again without sdk. We are so worried to be impacted on google play store as well.

**Comment by LaurynasM-iproyal** [comment]
It is quite regular for playstore to ask for justification and video showing the behavior of suspicious behavior. What we recommend is to record how the service is currently being used. Depending on that they might want to see different actions being taken by application. If our service is used to unlock certain benefits we would suggest recording that too, especially if user has to agree by clicking a button or checking a checkbox. Also, if not done already, check if you have added a dialog with disclaimer that notifies user about service being used. This provides transparency to the user and ensures google that you are not misusing user data. We suggest using this text:

**_"By using this app, you are agreeing to share your internet traffic, and, therefore, might incur various outcomes with it. The company shares your internet traffic with third-party IPRoyal Services FZE LLC operating Pawns.app. Thus, the usage of your internet sharing is governed by rules set by the following documents: [Link to Terms of Service] and [Link to Privacy Policy]. These documents outline the rules and regulations governing the use of Pawns.app and its functionalities “._**

If playstore requires written justification, we cannot provide a template for that as it varies from one application to another. We can only suggest mentioning what benefits it provides to your users and that this service is being used as a replacement or an addition to advertisements to help fund the application expenses and keep it free for all users.

Example: 

![image](https://github.com/IPRoyal/android-pawns-sdk-demo/assets/133742156/58988e5f-6363-48af-bd6c-ab2a2e7b2dea)

**Comment by Ayman-apps** [comment]
As a workaround, can you remove the permission from the sdk's manifest and to be added in app manifest. So in our case we will keep FOREGROUND_SERVICE_DATA_SYNC and will not add FOREGROUND_SERVICED_SPECIAL_USE until further notice. By adding FOREGROUND_SERVICE_DATA_SYNC the sdk should still operate normally in the foreground

**Comment by LaurynasM-iproyal** [comment]
Unfortunately, we are not willing to do any workarounds by changing our service type from specialUse to dataSync, because as I mentioned, dataSync is a temporary type, which will be removed in later versions. We recommend following google guidelines and their requests in regards of our SDK. Also, as mentioned before, inform your users by showing disclaimer dialog and provide written justification to PlayStore, if requested, by either using the text we provided or adding more information that matches your application.

**Comment by Ayman-apps** [comment]
I didn't ask you to change your service type. Just remove the permission from the sdk's manifest. Permissions should be added in the app level not inside the sdk. and mention this in the integration steps.

**Comment by LaurynasM-iproyal** [comment]
You are right, I misunderstood the request. This approach would increase SDK user setup steps as it would not happen "automatically", but we see some benefits of this approach as well. Most likely we will add this to our list and make amendments for the next version, otherwise I will update status here.

**Comment by LaurynasM-iproyal** [comment]
SDK now does not declare services in manifest. Also, Foreground service now checks manifest permissions and if consumer declared "data sync", but not "special use", then it will launch itself with "data sync" type. Although it is your responsibility do correctly adjust manifest service declaration to use data sync as well as adding uses-permission 

Available in version **1.2.0**
